version: "3.9"

services:
  app:
    build:
      context: .    # Contexto do build é onde o docker-compose.yml está localizado -> Dockerfile nesse diretório será utilizado para construir a imagem do container
      args:
        - DEV=true
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app  # Mudanças feitas no código serão refletidas imediatamente ao container. 
    command: >
      sh -c " python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=dev-db
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dev-db
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme


volumes:
  dev-db-data: